// import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }

// export const metadata: Metadata = {
//   metadataBase: new URL("https://www.innovativefinancialadvisory.com"),
//   title: {
//     default: "IFAC - Innovative Financial Advisory",
//     template: "%s | IFAC",
//   },
//   description:
//     "IFAC provides financial advisory, investment, and strategic consulting services in Lagos, Nigeria.",
//   openGraph: {
//     title: "IFAC - Innovative Financial Advisory",
//     description: "Your trusted financial advisory partner.",
//     url: "https://www.innovativefinancialadvisory.com",
//     siteName: "IFAC",
//     images: [
//       "/icons/favicon-32x32.png", // example OG image from your icons
//     ],
//     type: "website",
//     locale: "en_US",
//   },
//   twitter: {
//     card: "summary_large_image",
//     title: "IFAC - Innovative Financial Advisory",
//     description: "Your trusted financial advisory partner.",
//     images: ["/icons/favicon-32x32.png"],
//     creator: "@IFAC",
//   },
//   icons: {
//     icon: [
//       "/icons/favicon-32x32.png",
//       "/icons/favicon-16x16.png",
//       "/icons/favicon.ico",
//     ],
//     shortcut: ["/icons/favicon-32x32.png"],
//     apple: [
//       { url: "/icons/apple-touch-icon.png" },
//     ],
//     other: [
//       {
//         rel: "android-chrome-192x192",
//         url: "/icons/android-chrome-192x192.png",
//       },
//       {
//         rel: "android-chrome-512x512",
//         url: "/icons/android-chrome-512x512.png",
//       },
//     ],
//   },
//   robots: {
//     index: true,
//     follow: true,
//     googleBot: {
//       index: true,
//       follow: true,
//       "max-image-preview": "large",
//       "max-snippet": -1,
//       "max-video-preview": -1,
//     },
//   },
//   alternates: {
//     canonical: "https://www.innovativefinancialadvisory.com",
//   },
// };

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://www.innovativefinancialadvisory.com"),
  title: {
    default: "IFAC - Innovative Financial Advisory",
    template: "%s | IFAC",
  },
  description:
    "IFAC provides financial advisory, investment, and strategic consulting services in Lagos, Nigeria.",
  keywords: [
    "financial advisory",
    "investment",
    "consulting",
    "Lagos",
    "Nigeria",
    "IFAC",
    "wealth management",
    "strategic finance",
  ],
  openGraph: {
    title: "IFAC - Innovative Financial Advisory",
    description: "Your trusted financial advisory partner.",
    url: "https://www.innovativefinancialadvisory.com/",
    siteName: "IFAC",
    images: [
      {
        url: "/og-image.png", // ⚠️ Create this file for best previews
        width: 1200,
        height: 630,
        alt: "IFAC Financial Advisory",
      },
    ],
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "IFAC - Innovative Financial Advisory",
    description: "Your trusted financial advisory partner.",
    images: ["/og-image.png"],
  },
  icons: {
    icon: [
      { url: "/icons/favicon-32x32.png", sizes: "32x32" },
      { url: "/icons/favicon-16x16.png", sizes: "16x16" },
      { url: "/icons/favicon.ico" },
    ],
    apple: { url: "/icons/apple-touch-icon.png" },
    shortcut: { url: "/icons/favicon-32x32.png" },
    other: [
      { rel: "android-chrome-192x192", url: "/icons/android-chrome-192x192.png" },
      { rel: "android-chrome-512x512", url: "/icons/android-chrome-512x512.png" },
    ],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  alternates: {
    canonical: "https://www.innovativefinancialadvisory.com",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
